//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by FCWizard.rc
//
#define IDS_PROJNAME                    100
#define IDD_WIZARD_DIALOG               201
#define IDC_PANE_TAB                    201
#define IDD_PAGE_MSGMAP                 202
#define IDC_PROJECT_COMBO               203
#define IDC_CLASSNAME_COMBO             204
#define IDD_PAGE_WINX_PROP              204
#define IDC_FILENAME                    205
#define IDD_PAGE_WINX_EVENT             205
#define IDD_PAGE_WINX_NOTIFY            206
#define IDC_NOTIFY_LIST                 207
#define IDC_MEMBERFUNCTION_LIST         208
#define IDD_ADD_NOTIFY_DIALOG           208
#define IDC_ADDFUNCTION_BTN             209
#define IDD_PAGE_CLASSINFO              209
#define IDC_DELFUNCTION_BTN             210
#define IDD_PAGE_ABOUT                  210
#define IDC_PROPMAP_LIST                211
#define IDD_PAGE_WINX_DLSZ              211
#define IDC_EVENT_LIST                  212
#define IDD_EDIT_DLSZ_DIALOG            212
#define IDD_WINX_EDIT_DLSZ_DIALOG       212
#define IDC_EVENT_TOKEN_LIST            213
#define IDD_PAGE_WINX_FONT              213
#define IDD_PAGE_FONT                   213
#define IDC_CONTROL_LIST                214
#define IDD_PAGE_DLSZ                   214
#define IDC_MENU_LIST                   215
#define IDD_PAGE_WTL_DLSZ               215
#define IDD_WTL_EDIT_DLSZ_DIALOG        216
#define IDC_NOTIFY_TOKEN_LIST           217
#define IDC_RESDIALOG_COMBO             218
#define IDD_PAGE_NOTIFY                 218
#define IDC_RESMENU_COMBO               219
#define IDD_PAGE_DDX                    219
#define IDC_ADDEVENT_BTN                220
#define IDD_WTL_DDX_DIALOG              220
#define IDD_ADD_DDX_DIALOG              220
#define IDC_DELEVENT_BTN                221
#define IDD_PAGE_UPUI                   221
#define IDD_ADD_UPUI_DIALOG             222
#define IDC_PROP_LIST                   223
#define IDD_PAGE_EVENT                  223
#define IDC_PROP_TOKEN_LIST             224
#define IDD_ADD_WTLEVENT_DIALOG         224
#define IDC_ADDMSG_BTN                  225
#define IDC_ADDNOTIFY_BTN               225
#define IDD_PAGE_TOOLS                  225
#define IDC_DELMSG_BTN                  226
#define IDC_DELNOTIFY_BTN               226
#define IDD_PAGE_APPWIZARD              226
#define IDC_ADDCLASS_BTN                227
#define IDB_IMAGE                       227
#define IDC_FUNCTIONNAME_EDIT           229
#define IDR_PROP_TOOLBAR                229
#define IDC_NOTIFY_STATIC               230
#define IDC_OBJECTID_STATIC             231
#define IDD_PAGE_SETUP                  231
#define IDC_INFO_STATIC                 233
#define IDC_INFO_RESOURCE               234
#define IDC_EDITEVENT_BTN               235
#define IDC_EDITNOTIFY_BTN              236
#define IDC_INFO_BASECLASS              237
#define IDC_TOKEN_LIST                  242
#define IDC_ADDDLSZ_BTN                 243
#define IDC_DELDLSZ_BTN                 244
#define IDC_OBJECTID_COMBO              246
#define IDC_RESIZE_X                    248
#define IDC_RESIZE_Y                    249
#define IDC_RESIZE_ALL                  250
#define IDC_ANCHOR_RT                   251
#define IDC_ANCHOR_LB                   252
#define IDC_ANCHOR_RB                   253
#define IDC_ANCHOR_ALL                  254
#define IDC_TYPE_STATIC                 255
#define IDC_ADDFONT_BTN                 259
#define IDC_DELFONT_BTN                 260
#define IDC_ADDDLGFONT_BTN              261
#define IDC_EVENTKIND_BTN               262
#define IDC_EVENTLIST_BTN               263
#define IDC_EVENT_TREE                  264
#define IDC_VERSION_STATIC              267
#define IDC_CHECK1                      273
#define IDC_CHECK2                      274
#define IDC_CHECK3                      275
#define IDC_CHECK4                      276
#define IDC_CHECK5                      277
#define IDC_CHECK6                      278
#define IDC_CHECK7                      279
#define IDC_STATIC_PROJECT              281
#define IDC_RES_LIST                    283
#define IDC_ADDDDX_BTN                  285
#define IDC_DELDDX_BTN                  286
#define IDC_VAR_EDIT                    288
#define IDC_DDXTYPE_COMBO               289
#define IDC_VARTYPE_COMBO               290
#define IDC_LEN_EDIT                    291
#define IDC_MIN_EDIT                    292
#define IDC_MAX_EDIT                    293
#define IDC_ADDUPUI_BTN                 294
#define IDC_DELUPUI_BTN                 295
#define IDC_RESOURCE_LIST               296
#define IDC_RESTYPE_EDIT                297
#define IDC_MENUPOPUP_CHECK             298
#define IDC_MENUBAR_CHECK               299
#define IDC_CHILDWINDOW_CHECK           300
#define IDC_TOOLBAR_CHECK               301
#define IDC_STATUSBAR_CHECK             302
#define IDC_OBJECTID_EDIT               303
#define IDC_MSG_EDIT                    308
#define IDC_FUNCNAME_EDIT               309
#define IDC_FUNC_EDIT                   310
#define IDC_WTLNEW_CHECK                311
#define IDC_PAGE_TREE                   312
#define IDC_PAGE_STATIC                 313
#define IDC_LINE_STATIC                 314
#define IDC_PAGE_NAME                   315
#define IDC_APPWIZARD_LIST              316
#define IDC_GO_BTN                      317
#define IDC_APPWIZARD_INFO              318
#define IDC_ROOT_TREE                   319
#define IDC_EVENT_SPLIT                 321
#define IDC_RADIO1                      325
#define IDC_RADIO2                      326
#define IDC_RADIO3                      327
#define IDC_FRMPANEL                    328
#define IDC_ENABLE_WTL                  329
#define IDC_ENABLE_WINX                 330
#define IDC_ENABLE_APPWIZARD            331
#define IDC_ENABLE_CODEWIZARD           332
#define IDC_VFCSETUP_BTN                333
#define ID_PROP_CLASS                   32768
#define ID_PROP_ABC                     32769
#define ID_PROP_KIND                    32770
#define ID_PROP_LIST                    32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        232
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         334
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
