-- build by visualfc@gmail.com
-- lang file for ..\wiz_main.wlua

local lang = {}
lang["Project Name"] = "项目名称"
lang["Location"] = "本地目录"
lang["Browse"] = "浏览目录"
lang["Project Path"] = "项目路径"
lang["Make .dsp for VS60"] = "生成VS60项目"
lang["Make .vcproj for VS2002"] = "生成VS2002项目"
lang["Make .vcproj for VS2003"] = "生成VS2003项目"
lang["Make .vcproj for VS2005"] = "生成VS2005项目"
lang["Make .vcproj for VS2008"] = "生成VS2008项目"
lang["WTL_USE_SDK_ATL3 for VCExpress"] = "为VCExpress版本加入ATL3.0支持"
lang["WINVER undefine"] = "WINVER 未定义"
lang["WINVER = 0x0400"] = ""
lang["WINVER = 0x0500"] = ""
lang["WINVER = 0x0600"] = ""
lang["ATL/WTL AppWizard 8.0 - Step 1 of 3"] = "ATL/WTL应用程序向导8.0 步骤1 （共3步)"
lang["Application Name"] = "应用程序名称"
lang["Set Projects Application Name"] = "设置应用程序的项目名称"
lang["Select Application Type"] = "选择应用程序类型"
lang["SDI Application"] = "单文档应用程序"
lang["Multiple Threads SDI"] = "多线程单文档应用程序"
lang["MDI Application"] = "多文档应用程序"
lang["Tab View Application"] = "选项卡式应用程序"
lang["Explorer Application"] = "资源管理器式应用程序"
lang["Dialog Based"] = "对话框应用程序"
lang["Select project options"] = "选择项目类型"
lang["Enable ActiveX Control Hosting"] = "允许ActiveX控制"
lang["Create as a COM Server"] = "建立COM服务器"
lang["Generic .cpp Files"] = "允许生成.cpp文件"
lang["Add Common Control Manifest"] = "添加公用控件清单"
lang["Unicode character set"] = "使用UNICODE"
lang["Resource Language"] = "资源文件语言"
lang["Modal Dialog"] = "模式对话框"
lang["Frame Dialog (using vfcframe library)"] = "增强对话框(具有工具栏、状态栏等)(使用vfcframe库)"
lang["check it add vfcframe.h to projects"] = "添加vfcframe.h文件到项目中"
lang["ATL/WTL AppWizard 8.0 - Step 2 of 3"] = "ATL/WTL应用程序向导8.0 步骤2 （共3步)"
lang["Application Type"] = "应用程序类型"
lang["Selection Application Type"] = "选择应用程序类型"
lang["Select UI features"] = "选择详细用户界面"
lang["Toolbar"] = "工具栏"
lang["Rebar"] = "复合工具栏"
lang["Command Bar"] = "命令式菜单栏"
lang["Status Bar"] = "状态栏"
lang["Use a View Window"] = "使用视图窗口"
lang["View Type"] = "选择视图类型"
lang["Generic Window"] = "标准窗口"
lang["Form (Dialog Based)"] = "对话框窗口"
lang["ListBox"] = "列表控件"
lang["Edit"] = "编辑控件"
lang["List View"] = "列表视图"
lang["Tree View"] = "树状视图"
lang["Rich Edit"] = "RTF文档页面"
lang["HTML Page"] = "HTML页面"
lang["Scroll Window"] = "滚动视图"
lang["Host ActiveX Controls"] = "允许内嵌ActiveX支持"
lang["ATL/WTL AppWizard 8.0 - Step 3 of 3"] = "ATL/WTL应用程序向导8.0 步骤3 （共3步)"
lang["User Interface Features"] = "自定义界面"
lang["Selection Application User Interface Features"] = "选择应用程序自定义界面细节"
lang["< Prev"] = "< 上一步"
lang["Next >"] = "下一步 >"
lang["Cancel"] = "取消"
lang["Finish"] = "完成"
lang["Warning"] = "警告"
lang["Project Path or Name not Valid"] = "无效的项目路径或名称"
lang["Project path is exists "] = "项目路径已经存在 "
lang["Project Location is not exists "] = "项目根目录无效 "
lang["Project Location is exists "] = "无法找到项目路径"
lang["OK"] = "确认"
lang["New Project Infomation"] = "建立新项目的概况"

--ui("test str")
function ui(str)
	if lang[str] ~= nil and lang[str] ~= "" then
		return lang[str]
	else
		return str
	end
end

